---
title: "gluc07"
author: "Verena Steffen"
date: "May 23, 2016"
output: html_document
---

```{r,echo=FALSE}
# Clear workspace
rm(list=ls())
# Set working directory
setwd("/home/vreni/Dropbox/Zürich/Uni Zürich Biostatistik Master/4_FS_2016/STA490_StatisticalConsulting")
# Load libraries
library("knitr")
library("lattice")
library("plyr")
library("dplyr")
library("lme4")
library("ggplot2")
# Load data
load("STA490/glu_clean.RData")
# glu <- data$glu
# patients <- data$patients
# timediff <- data$timediff
```


Get better ward description
```{r}
translation <- read.csv("STA490/Einheiten.csv")
head(translation)

translation$Einsender %in% glu$Ward
# Not all listed Wards are in glu$Ward
```


NOT Wards
```{r}
# Subset NOT measurements
not <- glu[startsWith(as.character(glu$Ward), "NOT"),]
# Number of inpatient measurements NOT wards
summary(not$Inpatient)
pat <- tapply(not$Glu, not$PID, length)
table(pat)

# Only inpatients
not.inp <- glu[startsWith(as.character(glu$Ward), "NOT") & glu$Inpatient == 1,]
pat.inp <- tapply(not.inp$Glu, not.inp$PID, length)
table(pat.inp)
glu[glu$PID == 22608, c("Ward", "Glu", "Time")]  # max of measurement values in NOT wards
```

```{r}

load("STA490/models.RData")

# Modeling
library("lqmm")
fit1 <- lqmm(fixed = log(Glu) ~ Age + Sex + Ward, random = ~ 1 + Lab, group = PID, tau = 0.5, type = "normal", data = glu[1:10000, ])
fit1
plot(predict(fit1, newdata = 1:10000), ylim = c(-0.5, 4), pch = ".")
plot(log(glu[1:10000, "Glu"]), ylim = c(-0.5, 4), pch = ".")


fit2 <- lqmm(fixed = log(Glu) ~ Age + Sex + Ward, random = ~ 1 + Lab, group = PID, tau = 0.1, type = "normal", data = glu[1:10000, ])
fit2
plot(predict(fit2, newdata = 1:10000), ylim = c(-0.5, 4), pch = ".")
plot(log(glu[1:10000, "Glu"]), ylim = c(-0.5, 4), pch = ".")

dat <- data.frame(x = 1:10000, y=log(glu$Glu[1:10000]))
qs <- 1:9/10
#pdf("glu_quantiles.pdf")
ggplot(dat, aes(x,y)) + geom_point(cex=0.2) + geom_quantile(quantiles = qs) + theme_bw()
#dev.off()

# dat <- data.frame(x = 1:nrow(glu), y=log(glu$Glu))
# qs <- 1:9/10
# ggplot(dat, aes(x,y)) + geom_point(cex=0.1) + geom_quantile(quantiles = qs) + theme_bw()

# save(fit1, fit2, file = "models.RData")
```



```{r}
# Other biomarkers
colnames(glu)[4:17]

missings <- apply(glu[, 4:17], 2, function(x) sum(is.na(x)))
nrow(glu)-missings

# both scales represent the same patients
plot(HbA1c.IFCC ~ HbA1c.DCCT, data = glu, pch = 16, cex = 0.6)
mod <- lm(HbA1c.IFCC ~ HbA1c.DCCT, data = glu)
summary(mod)
plot(mod)

IFCC.na <- which(is.na(glu[, "HbA1c.IFCC"]))
DCCT.na <- which(is.na(glu[, "HbA1c.DCCT"]))
length(IFCC.na)
length(DCCT.na)
length(intersect(IFCC.na, DCCT.na))

# IFCC to DCCT
glu$dcct <- glu$HbA1c.IFCC/10.929+2.15
mol <- (c(0, 5, 10, 15)-2.15)*10.929
perc <- c(0, 50, 100, 150, 175)/10.929+2.15

# Scatter plots
hba1c <- geom_point(aes(x=(HbA1c.DCCT-2.15)*10.929), alpha=0.3, size=1)
ldlcalc <- geom_point(aes(y=LDL.calc), alpha=0.3, size=1)
gp <- geom_point(size=1, alpha=0.3)
labs <- scale_x_continuous(name="HbA1c", breaks = c(0, 50, 100, 150, 175), labels = c("0%\n0", "6.7%\n50", "11.3%\n100", "15.9%\n150", "\n(mmol/mol)"))
scm <- scale_colour_manual(values = c("black","firebrick3"))
leg <- theme(legend.position=c(0.9,0.88))

p1 <- ggplot(glu, aes(x=HbA1c.IFCC, y=Glu, col=diabetic)) + gp + theme_bw() + scm + leg + labs

p2 <- ggplot(glu, aes(x=HbA1c.IFCC, y=TG, col=diabetic)) + gp + theme_bw() + scm + leg + labs

p3 <- ggplot(glu, aes(x=HbA1c.IFCC, y=HDL, col=diabetic)) + gp + theme_bw() + scm + leg + labs

p4 <- ggplot(glu, aes(x=HbA1c.IFCC, y=LDL, col=diabetic)) + gp + theme_bw() + scm + leg + labs

pdf(file = "lipid.pdf")
p1 + hba1c
p2 + hba1c
p3 + hba1c
p4 + hba1c + ldlcalc + ylim(0,10)
dev.off()
```


Inter- and Intra-day-variability
```{r}
# Flag days from patients
g <- glu[1:100, c("PID", "Glu", "Time", "Inpatient", "cv")]

g12 <- g[g$PID == 12, ]

# mean per day

```


Modeling
```{r}
glu.subset <- glu[which(as.numeric(glu$PID)<10000), ]

library("lme4")
library("lattice")

fm01 <- lmer(log(Glu) ~ 1 + Age + Sex + Lab + (1 | Ward) + (1 | PID), data = glu, REML = FALSE)
pdf("STA490/plots/randef_wards.pdf")
qqmath(ranef(fm01, condVar = TRUE))[["Ward"]]
dev.off()

summary(fm01)
plot(fm01, pch = "x")

# fm1 <- lmer(log(Glu) ~ 1 + Age + Sex + Lab + (1 | Ward) + (1 + Age | PID), data = glu, REML = FALSE)
# fm2 <- lmer(log(Glu) ~ 1 + Age + Sex + Lab + (1 | Ward) + (1 | PID) + (0 + Age | PID), data = glu, REML = FALSE)
# save(fm1, fm2, file = "STA490/mods.rda")
load("STA490/mods.rda")
anova(fm1, fm2)


```


