---
title: "Glucose Project Version 5"
author: "Verena Steffen"
output: html_document
---

```{r initialize,echo=FALSE}
# Clear workspace
rm(list=ls())
# Set working directory
setwd("/home/vreni/Dropbox/Zürich/Uni Zürich Biostatistik Master/4_FS_2016/STA490_StatisticalConsulting")

load("STA490/glu_v05.RData")
```



```{r calculate cv,echo=FALSE}
# 
# # Add column for high variability inpatients
# CV <- function(mean, sd) (sd/mean)*100
# glu$cv <- rep(NA, nrow(glu))
# 
# npatients <- length(unique(glu$PID))  # 41428
# for (i in 1:npatients) {  # i: patient
#     pat.glu <- glu[which(as.numeric(glu$PID) == i), "Glu"]
#     pat.inp <- glu[which(as.numeric(glu$PID) == i), "Inpatient"]
#     glu[which(as.numeric(glu$PID) == i), "cv"] <- ifelse(pat.inp == TRUE, CV(mean(pat.glu), sd(pat.glu)), NA)
# }
# 
# glu$high.var15 <- ifelse(glu$cv > 15, 1, 0)
# glu$high.var20 <- ifelse(glu$cv > 20, 1, 0)
# glu$high.var30 <- ifelse(glu$cv > 30, 1, 0)
# 
# glu[which(as.numeric(glu$PID) <= 200), c("PID", "Time", "Inpatient", "cv", "high.var")]
```

A converter from the old units (DCCT (Diabetes Control and Complications Trial) in %) to the new units (IFCC (International Federation of Clinical Chemistry) in mmol/mol) can be found here: 
http://www.diabetes.co.uk/hba1c-units-converter.html

A patient is diabetic if minimum one measurement fulfills

- HbA1c >= 6.5 % (equal to HbA1c >= 48 mmol/mol) **OR**
- Glu >=11.1 mmol/l


```{r diabetic&glyc.contr def,echo=FALSE}
# Add column for diabetic yes/no
# old way (per measurement)
# glu$diabetic <- ifelse((glu$Glu >= 11.1) |
#                            (glu$HbA1c.IFCC >= 48 & !is.na(glu$HbA1c.IFCC)) |
#                            (glu$HbA1c.DCCT >= 6.5) & !is.na(glu$HbA1c.DCCT), 1, 0)

# # new way: per patient
# glu$diabetic <- rep(NA, nrow(glu))
# diabetic.patients <- 0
# npatients <- length(levels(glu$PID))
# for (i in 1:npatients) {
#     if (sum(glu[as.numeric(glu$PID) == i, "Glu"] >= 11.1 |
#                                    glu[as.numeric(glu$PID) == i, "HbA1c.IFCC"] >= 48 |
#                                    glu[as.numeric(glu$PID) == i, "HbA1c.DCCT"] >= 6.5,
#                                na.rm = TRUE) >=1) {
#         glu[as.numeric(glu$PID) == i, "diabetic"] <- 1
#         diabetic.patients <- diabetic.patients + 1
#     }
#     else {
#         glu[as.numeric(glu$PID) == i, "diabetic"] <- 0
#     }
# }

# save(glu, diabetic.patients, npatients, file = "STA490/glu_v04.RData")

#####################################################################################

# # Define status according to glycemic control ranges
# glu$glyc.control <- ifelse(glu$Glu < 2.2,
#             yes = "severe hypoglycemia",
#             no = ifelse(glu$Glu < 4,
#                         yes = "hypoglycemia",
#                         no = ifelse(glu$Glu < 7.8,
#                                     yes = "euglycemia",
#                                     no = ifelse(glu$Glu < 10.1,
#                                                 yes = "mild hyperglycemia",
#                                                 no = ifelse(glu$Glu < 15,
#                                                             yes = "pronounced hyperglycemia",
#                                                             no = "severe hyperglycemia")))))
```


```{r high variability def,echo=FALSE}
# glu$Inpatient <- as.factor(glu$Inpatient)
# glu$high.var15 <- as.factor(glu$high.var15)
# glu$high.var20 <- as.factor(glu$high.var20)
# glu$high.var30 <- as.factor(glu$high.var30)
# glu$diabetic <- as.factor(glu$diabetic)
# glu$glyc.control <- factor(glu$glyc.control,
#                            levels = c("severe hyperglycemia",
#                                       "pronounced hyperglycemia",
#                                       "mild hyperglycemia",
#                                       "euglycemia",
#                                       "hypoglycemia",
#                                       "severe hypoglycemia"))
# save(glu, file = "STA490/glu_v03.RData")
```


```{r}
# Histograms of the diabetes thresholds per measurement
par(mfrow=c(1,3),cex.axis=1, cex.lab=1, cex.main=1)
hist(glu$HbA1c.IFCC); abline(v = 48, col = 2, lwd = 3)
hist(glu$HbA1c.DCCT); abline(v = 6.5, col = 2, lwd = 3)
hist(glu$Glu); abline(v = 11.1, col = 2, lwd = 3)
par(mfrow=c(1,1),cex.axis=1, cex.lab=1, cex.main=1)

# Diabetic patients
# % diabetic patients
diab <- round(diabetic.patients/npatients * 100, 1)
diab

# Diabetic measurements
boxplot(Glu ~ diabetic, data = glu, pch = "*", log = "y", 
        main = "Glucose values of diabetic and non-diabetic patients", 
        xlab = "Diabetic no (0) and yes (1)",
        ylab = "Blood glucose in mmol/l")
abline(h = 11.1, col = 2)

# # Variability in diabetic vs. non-diabetic patients
# mean(glu[which(glu$diabetic == 1), "cv"], na.rm = TRUE)
# mean(glu[which(glu$diabetic == 0), "cv"], na.rm = TRUE)

```


### Create frequency tables

```{r,warning=FALSE}
# Which Wards have more than 5000 measurements?
library(plyr)
ward.count <- as.data.frame(table(glu$Ward))
# High variability by Ward with > 5,000 measurements
ward5000 <- ward.count$Var1[which(ward.count$Freq > 5000)]
t0 <- xtabs(~ high.var20 + factor(Ward), glu[glu$Ward %in% ward5000, ])
mosaicplot(t0, color = rainbow(length(t0)),
           main = "High variability distribution in Wards with >5,000 measurements",
           ylab = "Ward", xlab = "0: CV <= 20     1: CV > 20", las = 0)
t0
# High variability by Ward with 3000 to 5,000 measurements
ward3000 <- ward.count$Var1[which(ward.count$Freq > 3000 & ward.count$Freq <= 5000)]
t1 <- xtabs(~ high.var20 + factor(Ward), glu[glu$Ward %in% ward3000, ])
mosaicplot(t1, color = rainbow(length(t1)),
           main = "High variability distribution in Wards with 3000 to 5000 measurements",
           ylab = "Ward", xlab = "0: CV <= 20     1: CV > 20", las = 0)
t1

# High variability by Ward with 2000 - 3000 measurements
ward2000 <- ward.count$Var1[which(ward.count$Freq > 2000 & ward.count$Freq <= 3000)]
t2 <- xtabs(~ high.var20 + factor(Ward), glu[glu$Ward %in% ward2000, ])
mosaicplot(t2, color = heat.colors(length(t2), alpha = 0.6),
           main = "High variability distribution in Wards with 2000 - 3000 measurements",
           ylab = "Ward", xlab = "0: CV <= 20     1: CV > 20", las = 1)
t2

# High variability by Ward with all measurements
t.all <- xtabs(~ high.var30 + Ward, glu)

# ratio high variability : low variability
ratio <- t.all[2, ] / t.all[1, ]
plot(ratio ~ levels(glu$Ward.number), type = "h", 
     main = "Ratio high : low variability per Ward", 
     ylab = "ratio", xlab = "Ward",
     ylim = c(0, 6)
     )
abline(h = 1, col = 2)
text(380, 5.7, "high variability: CV >30 %")

# Glycemic control status
library(plyr)
library(dplyr)
glyc.contr <- as.data.frame(table(glu$glyc.control))
glyc.contr$p <- glyc.contr$Freq / nrow(glu)
knitr::kable(glyc.contr)

a <- glu %>% 
    group_by(glyc.control, high.var30) %>% 
    summarize(n = n())
knitr::kable(a)

# b <- glu %>% 
#     group_by(Ward, high.var30) %>% 
#     summarize(n = n())
# knitr::kable(b)

# CV by Ward
cv.ward <- aggregate(glu$cv, by = list(Ward = glu$Ward), FUN = mean, na.rm = TRUE)
head(cv.ward, 20)

plot(cv.ward$x[order(cv.ward$x)] ~ cv.ward$Ward, type = "h")
abline(h = 20, col = 3); abline(h = 30, col = 3)

################################################################################
# % outlier per Ward
# outlier: severe + pronounced hyper- + hypo- + severe hypoglycemia
# total <- rep(NA, length(levels(glu$Ward.number)))
# outliers <- rep(NA, length(levels(glu$Ward.number)))
# 
# for (w in 1:length(outliers)) {  # w: Wards
#     total[w] <- sum(glu$Ward.number == w)
#     outliers[w] <- sum((glu$glyc.control == "severe hyperglycemia" |
#                glu$glyc.control == "pronounced hyperglycemia" |
#                glu$glyc.control == "hypoglycemia" |
#                glu$glyc.control == "severe hypoglycemia") & glu$Ward.number == w)
# }
# 
# percent.outliers <- outliers/total*100
################################################################################
# save(glu,
#      diabetic.patients, npatients, diab,
#      outliers, total, percent.outliers, file = "STA490/glu_v05.RData")


plot(percent.outliers ~ levels(glu$Ward.number), type = "h",
     main = "Percent outliers/Ward vs Ward")
plot(percent.outliers ~ total, pch = "*", log = "x",
     col= ifelse(percent.outliers >= 50, "red", "black"),
     main = "Percent outliers/Ward vs. number of patients/Ward", cex = 1.5)
text(1000, 85, "outliers:\nsevere hyperglycemia\npronounced hyperglycemia\nhypoglycemia\nsevere hypoglycemia")

# How many patients were in the Wards with more than 50 % outliers?
total[which(percent.outliers > 50)]

```

















